VERSION  := 0.6.0
MKVER    := src/cb/mkver.go
PROJECTS := 	src/github.com/jlinoff/go/msg \
		src/github.com/jlinoff/go/run \
		src/github.com/golang/lint/golint \
		src/cb

all: install

install: pre-flight
	@ \
	MkVer="$(MKVER)" ; \
	Dts=$$(date) ; \
	echo "// Automatically generated by make."  > $${MkVer} ; \
	echo "package main"                        >> $${MkVer} ; \
	echo "const ("                             >> $${MkVer} ; \
	echo "  Version = \"$(VERSION)\""          >> $${MkVer} ; \
	echo "  BuildDate = \"$${Dts}\""           >> $${MkVer} ; \
	echo ")" >> $$MkVer
	@for Project in $(PROJECTS) ; do \
		export GOPATH=$$(pwd) ; \
		pushd $$Project ; \
		echo "$@: $$(basename $$Project)" ; \
		go $@ ; \
		popd ; \
	done

clean:
	rm -rf src/github.com/jlinoff src/github.com/golang/lint
	find . -name '*~' -delete
	find . -name '*log' -delete

bundle:
	gnutar -J -c -f $$(basename $$(pwd))-src.tar.xz \
		--exclude='\.git' \
		etc/cb/recipes/*.ini \
		etc/cb/recipes/*.inc \
		src/cb \
		src/github.com/jlinoff \
		src/golang.org/x/tools/go/gcimporter15 \
		src/github.com/golang/lint \
		test \
		Makefile
	@ls -l $$(basename $$(pwd))-src.tar.xz

.PHONY: test
test: bin/cb
	bin/cb -q help list-files
	bin/cb -q --list
	bin/cb list-files
	bin/cb -q test-info
	bin/cb test-script

edit: src/github.com/golang/lint/README.md
	PATH="$$(pwd)/bin:$${PATH}" \
	GOPATH=$$(pwd) \
	/opt/atom/Atom.app/Contents/MacOS/Atom

golint: src/github.com/golang/lint/README.md

pre-flight:	src/github.com/golang/lint/README.md \
		src/github.com/jlinoff/go/msg/msg.go \
		src/github.com/jlinoff/go/run/run.go

src/github.com/golang/lint/README.md:
	GOPATH=$$(pwd) go get -u golang.org/x/tools/go/gcimporter15
	GOPATH=$$(pwd) go get -u github.com/golang/lint/golint

src/github.com/jlinoff/go/msg/msg.go:
	GOPATH=$$(pwd) go get -u github.com/jlinoff/go/msg/

src/github.com/jlinoff/go/run/run.go:
	GOPATH=$$(pwd) go get -u github.com/jlinoff/go/run/

update:
	GOPATH=$$(pwd) go get -u golang.org/x/tools/go/gcimporter15
	GOPATH=$$(pwd) go get -u github.com/golang/lint/golint
	GOPATH=$$(pwd) go get -u github.com/jlinoff/go/msg/
	GOPATH=$$(pwd) go get -u github.com/jlinoff/go/run/

